[package]
name = "hello"
version = "0.1.0"
authors = ["Artem Kozachenko <artem.kozachenko@ring.com>"]
edition = "2018"

[dependencies]
iron = "0.5.1"
mime = "0.2.3"
router = "0.5.1"
undercoded = "0.5.0"

